name: CICD for Vite Build and Deploy for Node Web App to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
 run:
    working-directory: ./hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: hello-world/dist  
          if-no-files-found: error

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist  

    #   - name: Deploy to Azure Web App
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: 'vite-node-web-app'
    #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #       package: dist
